# Generated by Django 5.2 on 2025-04-30 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_customer_email_remove_customer_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model',
            name='body_type',
        ),
        migrations.RemoveField(
            model_name='model',
            name='year',
        ),
    ]
