# Generated by Django 5.2 on 2025-04-30 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_add_year_to_car'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='description',
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.IntegerField(default=2024, verbose_name='Год выпуска'),
        ),
    ]
